// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcAXlT6hoou41oEgIbjRTCagAJzBTsZIM',
    appId: '1:854189510560:web:4e6e9f73ae347af536dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    authDomain: 'kasie-transie-3.firebaseapp.com',
    storageBucket: 'kasie-transie-3.appspot.com',
    measurementId: 'G-BQW5ZWEKB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3finIgPi481q3-GaEDjOLcoPbs664gTs',
    appId: '1:854189510560:android:68855664bb69532a36dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    storageBucket: 'kasie-transie-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCW2jYebHUN609zOFxgTnm0JWP-1Y40s',
    appId: '1:854189510560:ios:877bb819f706dafd36dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    storageBucket: 'kasie-transie-3.appspot.com',
    iosClientId: '854189510560-1p65sk1d1fgd0cg7nu15g9dhj81har7p.apps.googleusercontent.com',
    iosBundleId: 'com.boha.ambassadorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBCW2jYebHUN609zOFxgTnm0JWP-1Y40s',
    appId: '1:854189510560:ios:877bb819f706dafd36dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    storageBucket: 'kasie-transie-3.appspot.com',
    iosClientId: '854189510560-1p65sk1d1fgd0cg7nu15g9dhj81har7p.apps.googleusercontent.com',
    iosBundleId: 'com.boha.ambassadorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcAXlT6hoou41oEgIbjRTCagAJzBTsZIM',
    appId: '1:854189510560:web:92012013b5fdcca636dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    authDomain: 'kasie-transie-3.firebaseapp.com',
    storageBucket: 'kasie-transie-3.appspot.com',
    measurementId: 'G-B6X6MRC2JS',
  );
}
